[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Networks library for deploying and interacting with CosmWasm smart-contracts"
edition     = { workspace = true }
keywords    = ["cosmwasm", "blockchain"]
license     = { workspace = true }
name        = "cw-orch-networks"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.24.10"

exclude = [".env"]

[dependencies]
cw-orch-core = { workspace = true }
serde        = { workspace = true }
