[workspace]
exclude = [
  "test_contracts/compatibility-test", # TODO: add new after cw-orch-core 2.0.0 as it's breaking, it shouldn't be compatible
]
members = [
  "cw-orch",
  "cw-orch-daemon",
  "cw-orch-interchain",
  "packages/cw-orch-core",
  "packages/cw-orch-mock",
  "packages/cw-orch-networks",
  "packages/clone-testing",
  "packages/cw-orch-osmosis-test-tube",
  "packages/cw-orch-neutron-test-tube",
  "packages/cw-orch-traits",
  "test_contracts/*",
  "packages/macros/*",
  "packages/interchain/*",
  "packages/integrations/*",
]
resolver = "2"

[workspace.package]
authors    = ["CyberHoward <cyberhoward@protonmail.com>"]
edition    = "2021"
license    = "LGPL-3.0"
repository = "https://github.com/AbstractSDK/cw-orchestrator"

[workspace.dependencies]
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }

cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test", branch = "mvp" }
cosmos-sdk-proto = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "main" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
neutron-test-tube = { git = "https://github.com/permissionlessweb/neutron-test-tube", branch = "dev" }
osmosis-test-tube = { git = "https://github.com/permissionlessweb/osmosis-test-tube", branch = "cw3" }
cosmrs = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "main" }
ibc-proto = { git = "https://github.com/permissionlessweb/ibc-proto-rs", branch = "main" }
clone-cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "cw3/adapt_for_local_execution" }
osmosis-std = { git = "https://github.com/permissionlessweb/osmosis-rust", branch = "cw3" }
neutron-std = { git = "https://github.com/permissionlessweb/neutron-std", branch = "feat/cw3" }
simple-ica = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }
simple-ica-controller = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }
simple-ica-host = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }
tendermint = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }
tendermint-proto = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }
tendermint-rpc = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }

anyhow = "1.0"
serde  = { version = "1.0.208", default-features = false, features = ["derive"] }
tokio  = { version = "1.39", features = ["full"] }

cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "cw3" }
cw-orch-core     = { path = "packages/cw-orch-core" }
cw-orch-daemon   = { path = "./cw-orch-daemon" }
cw-orch-mock     = { path = "packages/cw-orch-mock" }
cw-orch-networks = { path = "packages/cw-orch-networks" }
cw-orch-traits   = { path = "packages/cw-orch-traits" }

# Macros
cw-orch-contract-derive = { path = "packages/macros/cw-orch-contract-derive", version = "0.21.0" }
cw-orch-fns-derive      = { path = "packages/macros/cw-orch-fns-derive", version = "0.23.0" }

# Extensions
cw-orch-neutron-test-tube = {  version = "0.1.0", path = "packages/cw-orch-neutron-test-tube" }
cw-orch-osmosis-test-tube = { version = "0.4.0", path = "packages/cw-orch-osmosis-test-tube" }

#Clone Testing
cw-orch-clone-testing = { version = "0.8.0", path = "packages/clone-testing" }

# Interchain
cw-orch-interchain        = { path = "cw-orch-interchain", version = "0.8.0" }
cw-orch-interchain-core   = { path = "packages/interchain/interchain-core", version = "0.9.0" }
cw-orch-interchain-daemon = { path = "packages/interchain/interchain-daemon", version = "0.9.0" }
cw-orch-interchain-mock   = { path = "packages/interchain/interchain-mock", version = "0.9.0" }
cw-orch-proto             = { path = "packages/interchain/proto", version = "0.9.0" }
cw-orch-starship          = { path = "packages/interchain/starship", version = "0.7.0" }


prost       = "0.14.1"
prost-types = "0.14.1"
serde_json  = "1.0.125"
sha2        = { version = "0.10.8" }
thiserror   = { version = "1.0.63" }
tonic       = { version = "0.14.1", features = ["codegen"] }
# Test deps
speculoos = "0.11.0"

# Logging
log = "0.4.22"

# Interchain / Hermes relayer
ibc-chain-registry = { path = "../hermes/crates/chain-registry" }
ibc-relayer-types  = { path = "../hermes/crates/relayer-types" }

