[package]
description = "Mock constract for cw-orch macro testing"
edition     = { workspace = true }
keywords    = ["cosmwasm", "blockchain"]
name        = "mock-contract"
version     = "0.1.0"

exclude = [".env"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default   = ["export"]
export    = []
interface = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-orch         = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { path = "../../../../ZK/cw/zk-cw-minus/packages/cw2" }
schemars = "0.8"
serde           = { workspace = true }
serde_json      = "1.0.125"
thiserror       = { version = "1.0.63" }
