[package]
authors.workspace    = true
description          = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-mock"
repository.workspace = true
version              = "0.24.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std  = { workspace = true, features = ["cosmwasm_1_2"] }
cw-multi-test = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw-orch-core  = { workspace = true }
cw-utils      = { workspace = true }
log           = { workspace = true }
serde         = { workspace = true }
sha2          = { workspace = true }

[dev-dependencies]
cw20             = { version = "3.0.0", git = "https://github.com/permissionlessweb/cw-plus" }
cw20-base        = { version = "3.0.0", git = "https://github.com/permissionlessweb/cw-plus" }
speculoos = { workspace = true }

anyhow        = { workspace = true }
mock-contract = { path = "../../contracts-ws/contracts/mock_contract" }
