[package]
description   = "cw-orch interfaces for cw-plus base contracts"
documentation = "https://orchestrator.abstract.money"
edition       = "2021"
homepage      = "https://abstract.money"
license       = "Apache-2.0"
name          = "cw-plus-orch"
repository    = "https://github.com/AbstractSDK/cw-orchestrator"
version       = "0.25.0"                                         # Version of cw-orch that's used

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { version = "3.0.1" }
cosmwasm-std    = { workspace = true }
cw-utils        = { workspace = true }


cw-controllers     = { version = "3.0.0" }
cw1                = { package = "cw1", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3" }
cw1-subkeys        = { package = "cw1-subkeys", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw1-whitelist      = { package = "cw1-whitelist", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw20               = { package = "cw20", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3" }
cw20-base          = { package = "cw20-base", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw20-ics20         = {  git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw3                = { package = "cw3", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3" }
cw3-fixed-multisig = { package = "cw3-fixed-multisig", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw3-flex-multisig  = { package = "cw3-flex-multisig", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw4                = { package = "cw4", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3" }
cw4-group          = { package = "cw4-group", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }
cw4-stake          = { package = "cw4-stake", git = "https://github.com/permissionlessweb/cw-plus", branch = "bump/v3", features = ["library"] }

cw-orch-from-interface-derive = { version = "0.1.0", path = "../../macros/from-interface-derive" }

cw-orch = { workspace = true }

[dev-dependencies]
cw-orch            = { workspace = true, features = ["daemon"] }
cw-orch-interchain = { workspace = true }
dotenv             = "0.15.0"
octocrab           = "0.39.0"
pretty_env_logger  = "0.5.0"
reqwest            = "0.12.7"
tokio.workspace    = true
