[workspace]

members = ["contracts/*"]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
cosmwasm-std    = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
cw20             = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20-base        = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }

anyhow = "1.0"
log    = "0.4.14"
serde  = { version = "1.0.103", default-features = false, features = ["derive"] }

cw-orch            = { path = "../cw-orch", version = "0.30.0" }
cw-orch-interchain = { path = "../cw-orch-interchain", version = "0.8.1" }

# Unify crates.io transitive deps with our git forks
[patch.crates-io]
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-core = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-crypto = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-schema-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-schema-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
