[workspace]

members = ["contracts/*"]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "zk-mvp" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "zk-mvp" }

anyhow = "1.0"
log    = "0.4.14"
serde  = { version = "1.0.103", default-features = false, features = ["derive"] }

cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-interchain = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }

# Unify crates.io transitive deps with our git forks
[patch.crates-io]















cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-core = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-crypto = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-schema-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-schema-derive = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }