[package]
authors.workspace    = true
description          = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-clone-testing"
repository.workspace = true
version              = "0.9.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }

cw-orch-core   = { workspace = true }
cw-orch-daemon = { workspace = true }
cw-orch-mock   = { workspace = true }

clone-cw-multi-test = {  version = "3.0.1", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "cw3/adapt_for_local_execution" }

anyhow    = { workspace = true }
cw-utils  = { workspace = true }
itertools = "0.12.0"
log       = { workspace = true }
serde     = { workspace = true }
sha2      = "0.10.8"
tokio     = { workspace = true }
tonic     = { workspace = true }

[dev-dependencies]
cosmwasm-schema = "3.0.1"
speculoos       = { workspace = true }

cw20             = { version = "3.0.0", git = "https://github.com/permissionlessweb/cw-plus" }
cw20-base        = { version = "3.0.0", git = "https://github.com/permissionlessweb/cw-plus" }

counter-contract  = { path = "../../contracts-ws/contracts/counter" }
cw-orch           = { path = "../../cw-orch", features = ["daemon"] }
env_logger        = "0.10.0"
pretty_env_logger = "0.5.0"
